# fly.toml app configuration file generated for tudoi on 2023-04-29T02:53:44-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tudoi"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
