databases:
  - name: postgres
    inAllowList: []

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KRY
        sync: false
      - key: DATABASE_URL  
        fromDatabase:
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    inAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
